export const EMPLOYEE_STATE = Object.freeze({
  CREATED: "CREATED",
  IDLE: "IDLE",
  WORKING: "WORKING",
  WAITING: "WAITING",
  SLEEPING: "SLEEPING",
  RESUME: "RESUME",
  FINISHED: "FINISHED",
});

export const EMPLOYEE_TRANSITIONS = Object.freeze({
  [EMPLOYEE_STATE.CREATED]: new Set([EMPLOYEE_STATE.IDLE]),
  [EMPLOYEE_STATE.IDLE]: new Set([EMPLOYEE_STATE.WORKING, EMPLOYEE_STATE.SLEEPING, EMPLOYEE_STATE.FINISHED]),
  [EMPLOYEE_STATE.WORKING]: new Set([EMPLOYEE_STATE.IDLE, EMPLOYEE_STATE.WAITING, EMPLOYEE_STATE.SLEEPING, EMPLOYEE_STATE.FINISHED]),
  [EMPLOYEE_STATE.WAITING]: new Set([EMPLOYEE_STATE.WORKING, EMPLOYEE_STATE.SLEEPING, EMPLOYEE_STATE.FINISHED]),
  [EMPLOYEE_STATE.SLEEPING]: new Set([EMPLOYEE_STATE.RESUME, EMPLOYEE_STATE.FINISHED]),
  [EMPLOYEE_STATE.RESUME]: new Set([EMPLOYEE_STATE.IDLE, EMPLOYEE_STATE.WORKING, EMPLOYEE_STATE.FINISHED]),
  [EMPLOYEE_STATE.FINISHED]: new Set(),
});

export function canTransitionEmployee(from, to) {
  return EMPLOYEE_TRANSITIONS[from]?.has(to) || false;
}
